# footprint: [[-0.3, 0.24], [0.3, 0.24], [0.3, -0.24],[-0.3, -0.24]]
robot_radius: 0.22

transform_tolerance: 0.2
map_type: costmap

obstacle_layer:
  enabled: true
  obstacle_range: 5
  raytrace_range: 10
  track_unknown_space: false
  combination_method: 1

  # observation_sources: laser_scan_sensor
  observation_sources: point_cloud_sensor laser_scan_sensor

  point_cloud_sensor:
    sensor_frame: velodyne
    data_type: PointCloud2
    topic: /velodyne_points
    marking: true
    clearing: true
    min_obstacle_height: -0.5
    max_obstacle_height: 1

  laser_scan_sensor:
    sensor_frame: laser
    data_type: LaserScan
    topic: hokoyo_filtered
    marking: true
    clearing: true

  # point_cloud_sensor:
  #   sensor_frame: livox_frame
  #   data_type: PointCloud2
  #   topic: /livox_overlap
  #   marking: true
  #   clearing: false
  #   min_obstacle_height: -0.5
  #   max_obstacle_height: 0.5

inflation_layer:
  enabled:              true
  cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
  # inflation_radius:     0.2 # garage  # max. distance from an obstacle at which costs are incurred for planning paths.
  inflation_radius:     0.1 # indoor  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
  map_topic:            "/map"
